specVersion: 0.0.5
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
	- grafting
graft:
	base: {{subgraphId}} # Subgraph ID of base subgraph
	block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
	- kind: enthereum/contract
		name: Receivable
		network: {{ network }}
		source:
			address: "{{ Receivable.address }}"
			abi: Receivable
			startBlock: {{ Receivable.startBlock }}
		mapping:
			kind: ethereum/events
			apiVersion: 0.0.7
			language: wasm/assemblyscript
			entities: []
			abis:
				- name: Receivable
					file: ./abis/Receivable.json
			eventHandlers:
        - event: AssetBurned(indexed uint256)
          handler: handleAssetBurned
        - event: AssetCreated(indexed address,indexed address,indexed uint256,uint256,uint256)
          handler: handleAssetCreated
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
      file: ./protocols/isle-finance-v0/src/mapping.ts
	- kind: ethereum/contract	
		name: WithdrawalManager
		network: {{ network }}
		source:
			address: "{{ WithdrawalManager.address }}"
			abi: WithdrawalManager
			startBlock: {{ WithdrawalManager.startBlock }}
		mapping:
			kind: ethereum/events
			apiVersion: 0.0.7
			language: wasm/assemblyscript
			entities: []
			abis:
				- name: WithdrawalManager
					file: ./abis/WithdrawalManager.json
				- name: LoanManager
					file: ./abis/LoanManager.json
				- name: PoolConfigurator
					file: ./abis/PoolConfigurator.json
			eventHandlers:
				- event: WithdrawalCancelled(indexed address)
					handler: handleWithdrawalCancelled
				- event: WithdrawalProcessed(indexed address,uint256,uint256)
					handler: handleWithdrawalProcessed
				- event: WithdrawalUpdated(indexed address,uint256,uint64,uint64)
					handler: handleWithdrawalUpdated
			file: ./protocols/isle-finance-v0/src/mapping.ts
	- kind: ethereum/contract
		name: LoanManager
		network: {{ network }}
		source:
			address: "{{ LoanManager.address }}"
			abi: LoanManager
			startBlock: {{ LoanManager.startBlock }}
		mapping:
			kind: ethereum/events
			apiVersion: 0.0.7
			language: wasm/assemblyscript
			entities: []
			abis:
				- name: LoanManager
					file: ./abis/LoanManager.json
				- name: WithdrawalManager
					file: ./abis/WithdrawalManager.json
				- name: PoolConfigurator
					file: ./abis/PoolConfigurator.json
			eventHandlers:
				- event: AccountingStateUpdated(uint256,uint112)
					handler: handleAccountingStateUpdated
				- event: FeesPaid(indexed uint16,uint256,uint256)
					handler: handleFeesPaid
				- event: FundsDistributed(indexed uint16,uint256,uint256)
					handler: handleFundsDistributed
				- event: FundsWithdrawn(indexed uint16,uint256)
					handler: handleFundsWithdrawn
				- event: ImpairmentRemoved(indexed uint16,uint256)
					handler: handleImpairmentRemoved
				- event: IssuanceParamsUpdated(indexed uint48,uint256,uint112)
					handler: handleIssuanceParamsUpdated
				- event: LoanImpaired(indexed uint16,uint256)
					handler: handleLoanImpaired
				- event: LoanRepaid(indexed uint16,uint256,uint256)
					handler: handleLoanRepaid
				- event: LoanRequested(indexed uint16)
					handler: handleLoanRequested
				- event: PaymentAdded(indexed uint16,indexed
						uint256,uint256,uint256,uint256,uint256,uint256)
					handler: handlePaymentAdded
				- event: PaymentRemoved(indexed uint16,indexed uint256)
					handler: handlePaymentRemoved
				- event: PrincipalOutUpdated(uint128)
					handler: handlePrincipalOutUpdated
				- event: UnrealizedLossesUpdated(uint128)
					handler: handleUnrealizedLossesUpdated
			file: ./protocols/isle-finance-v0/src/mapping.ts
	- kind: ethereum/contract
		name: PoolConfigurator
		network: {{ network }}
		source:
			address: "{{ PoolConfigurator.address }}"
			abi: PoolConfigurator
			startBlock: {{ PoolConfigurator.startBlock }}
		mapping:
			kind: ethereum/events
			apiVersion: 0.0.7
			language: wasm/assemblyscript
			entities: []
			abis:
				- name: PoolConfigurator
					file: ./abis/PoolConfigurator.json
				- name: WithdrawalManager
					file: ./abis/WithdrawalManager.json
				- name: LoanManager
					file: ./abis/LoanManager.json
			eventHandlers:
				- event: AdminFeeSet(uint256)
					handler: handleAdminFeeSet
				- event: BaseRateSet(uint96)
					handler: handleBaseRateSet
				- event: BuyerSet(indexed address)
					handler: handleBuyerSet
				- event: CoverDeposited(uint256)
					handler: handleCoverDeposited
				- event: CoverLiquidated(uint256)
					handler: handleCoverLiquidated
				- event: CoverWithdrawn(uint256)
					handler: handleCoverWithdrawn
				- event: MaxCoverLiquidationSet(uint24)
					handler: handleMaxCoverLiquidationSet
				- event: MinCoverSet(uint104)
					handler: handleMinCoverSet
				- event: OpenToPublicSet(bool)
					handler: handleOpenToPublicSet
				- event: PoolLimitSet(uint104)
					handler: handlePoolLimitSet
				- event: RedeemProcessed(indexed address,uint256,uint256)
					handler: handleRedeemProcessed
				- event: RedeemRequested(indexed address,uint256)
					handler: handleRedeemRequested
				- event: SharesRemoved(indexed address,uint256)
					handler: handleSharesRemoved
				- event: ValidLenderSet(indexed address,bool)
					handler: handleValidLenderSet
				- event: ValidSellerSet(indexed address,bool)
					handler: handleValidSellerSet
			file: ./protocols/isle-finance-v0/src/mapping.ts